site_name: 'Single cell sequencing data analysis - an introductiory but comprehensive course'
nav:
    - 'Course Introduction': index.md
    - 'Python':
      - Read the data: python/Part01_read_the_data.ipynb
      - Preprocessing: python/Part02_filtering_sample2.ipynb
      - Normalize and integrate: python/Part03_normalize_and_integrate.ipynb
      - Clustering and Differential Expression: python/Part04_clustering.ipynb
      - Pseudotimes and Cell Fate: python/Part05_cell_fate.ipynb
    - 'R':
      - Data analysis: scRNAseq_Seurat.md
docs_dir: develop
site_dir: docs
plugins:
    - mkdocs-jupyter
extra_css:
    - extra.css
theme: 
    name: material
    #logo: 'img/logo.png'
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
