# Project information
site_name: 'Single cell sequencing data analysis - an introductiory but comprehensive course'
site_url: 'https://hds-sandbox.github.io/scRNASeq_course/' # This should be the final hosting url
site_author: Samuele Soraggi and Jose Alejandro Romero Herrera
site_description: >-
  This course is an introduction for how to approach single cell RNAseq data, starting from the count matrix. 
  It will provide an overview of the fundamentals of scRNAseq analysis, including data QC, normalization, exploration with PCAs and heatmaps, performing differential expression analysis and annotation of the differentially expressed genes. 
  Participants will also learn how to evaluate confounding and batch effects in the data. 

# Repository
repo_name: hds-sandbox/scRNASeq_course
repo_url: https://github.com/hds-sandbox/scRNASeq_course

# Configuration
theme:

  # Use the Material for MkDocs theme
  # url: https://squidfunk.github.io/mkdocs-material/

  name: material
  custom_dir: overrides

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    # Sandbox colours - "brightness" and "slate" - are defined in stylesheets/extra.css 
    # Palette toggle for light mode
    - scheme: brightness
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  
  favicon: img/favicon.png
  logo: img/logo.png

# Changes to website colours and image parameters
extra_css:
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/embed-amd.js

plugins:
  - tags:
      tags_file: keywords.md
  - bibtex:
      bib_file: references.bib
  - search
  - mkdocs-video # embed videos to the docs
  # minify HTML of a page before it is written to disk
  - minify:
      minify_html: true
  - mkdocs-jupyter

# Analytics and social media
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hds-sandbox/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ucph_heads
  homepage: http://hds-sandbox.github.io/ 

# Extensions
markdown_extensions:
  - abbr # abbreviations   
  - admonition  
  - attr_list # Add HTML/CSS to Markdown elements  
  - def_list # Definition lists  
  - footnotes  
  - md_in_html  
  - toc: # Table of contents  
      permalink: true # Adds anchor link, can customise symbol with emoji  

  - tables  

  # Python extensions - can see descriptions  
  # at https://facelessuser.github.io/pymdown-extensions/  

  - pymdownx.arithmatex: # LaTeX  
      generic: true  
  - pymdownx.betterem: # improves emphasis (bold/italic) handling  
      smart_enable: all   
  - pymdownx.critic # useful for marking .md file without changes to html  
  - pymdownx.caret # improved functionality for caret symbol  
  - pymdownx.details # collapsable elements that hide content  
  - pymdownx.emoji: 
      emoji_generator: !!python/name:materialx.emoji.to_svg  
      emoji_index: !!python/name:materialx.emoji.twemoji  
      options:
        custom_icons:
          - overrides/.icons      
  - pymdownx.highlight: # code highlighting  
      anchor_linenums: true  
  - pymdownx.inlinehilite # inline code highlight  
  - pymdownx.keys # to make entering and styling keyboard key presses easier  
  - pymdownx.mark # highlight/mark text  
  - pymdownx.smartsymbols # special characters (e.g. arrows, tm, fractions)  
  - pymdownx.superfences # arbitrary nesting of code and content blocks inside each other
  - pymdownx.tabbed: # add tabs to .md file
      alternate_style: true
  - pymdownx.tasklist: # checkbox task list  
      custom_checkbox: true
  - pymdownx.tilde # delete and subscript
  - neoteroi.cards

# Extra configs
use_directory_urls: false
docs_dir: develop # source md files should be saved in the develop folder
site_dir: docs # built webpage will be created in the docs folder
copyright: CC-BY-SA 4.0 license

# Page tree
# include your page titles and associating .md files here

nav:
- 'Course Introduction': index.md
- 'Python':
  - Setup and installation: python/installation.md
  - Read the data: python/Part01_read_the_data.ipynb
  - Preprocessing: python/Part02_filtering_sample2.ipynb
  - Normalize and integrate: python/Part03_normalize_and_integrate.ipynb
  - Clustering and Differential Expression: python/Part04_clustering.ipynb
  - Pseudotimes and Cell Fate: python/Part05_cell_fate.ipynb
  - Gene enrichment: python/Part06_Condition_analysis.ipynb
  - 'Extra':
      - Preprocessing a sample': python/Part02_filtering_sample3.ipynb
      - Preprocessing a low quality sample: python/Part02_filtering_sample1.ipynb
- 'R':
  - Read the data: R/Part01_read_the_data.md
  - Preprocessing: R/Part02_filtering_sample2.md
  - Normalization: R/Part03_normalize_and_dim_reduc.md
  - Integration: R/Part04_integration.md
  - Clustering and Differential Expression: R/Part05_clustering.md
  - Pseudotimes: R/Part06_pseudotime.md
  - 'Extra':
      - Preprocessing another sample: R/Part02_filtering_sample3.md
