name: default
channels:
    - hds.sandbox
    - conda-forge
    - bioconda
    - nodefaults
    - pwwang
dependencies:
    - bioconductor-loomexperiment
    - bioconductor-singlecellexperiment
    - bioconductor-slingshot
    - bioconductor-spatialexperiment
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-org.dm.eg.db
    - bioconductor-genomicranges
    - bioconductor-scater
    - hds.sandbox::r-annotables
    - bioconductor-ucell
    - bowtie2
    - eggnog-mapper
    - fastp
    - fastqc
    - gatk4
    - glpk
    - graphviz
    - gxx_linux-64
    - hisat2
    - interproscan
    - ipykernel
    - ipywidgets
    - kallisto
    - loompy
    - multiqc
    - rpy2
    - anndata2ri
    - bbknn
    - gseapy
    - r-globals>=0.16.1
    - r-parallelly>=1.34.0
    - r-harmony>=1.0.1
    - r-irkernel
    - r-reticulate>=1.35
    - r-sctransform
    - r-seurat>5.0.0
#    - r-seurat-data
#    - r-seurat-disk
#    - r-seuratwrappers
    - r-wgcna
    - r-qlcmatrix
    - rsem
    - salmon
    - sambamba
    - samtools
    - scanpy
    - scrublet
    - slurm
    - snakemake
    - sortmerna
    - star
    - stringtie
    - subread
    - trimmomatic
    - pandas
    - matplotlib
    - plotly
    - ipywidgets
    - pytest
    - geopandas # for bento-tools
    - cellpose  # for bento-tools
    - cython
    - numpy>=2
    - pip:
        - jupyterquiz
        - rseqc
        - glmpca
